name = "Vanilla+"
author = "Laraka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc05fd13c97f30e40711ca6d10c2a20cfbd3b3599b06b5d8a9dbd5b581cdac7a"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1.2", "26.1.1", "1.21.4", "1.21.1", "1.21"]
