name = "Vanilla+"
author = "Laraka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a1731896d604221caa9ed77bb9d3e4db619296aa5e64d8a996291e0963cea84"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
